// Tüm menü verilerini içeren data dosyası
export const fullMenuKategoriler = [
  { id: "cat-kahvalti", nameTR: "Kahvaltı", nameEN: "Breakfast", slug: "kahvalti", sortOrder: 1 },
  { id: "cat-corbalar", nameTR: "Çorbalar", nameEN: "Soups", slug: "corbalar", sortOrder: 2 },
  { id: "cat-baslangiclar", nameTR: "Başlangıçlar & Atıştırmalıklar", nameEN: "Starters & Appetizers", slug: "baslangiclar-atistirmaliklar", sortOrder: 3 },
  { id: "cat-salatalar", nameTR: "Salatalar", nameEN: "Salads", slug: "salatalar", sortOrder: 4 },
  { id: "cat-phuket-imza", nameTR: "Phuket İmza Yemekleri", nameEN: "Phuket Signature Dishes", slug: "phuket-imza-yemekleri", sortOrder: 5 },
  { id: "cat-deniz-urunleri", nameTR: "Deniz Ürünleri", nameEN: "Seafood", slug: "deniz-urunleri", sortOrder: 6 },
  { id: "cat-bati-anayemekleri", nameTR: "Batı Ana Yemekleri", nameEN: "Western Main Courses", slug: "bati-anayemekleri", sortOrder: 7 },
  { id: "cat-comfort-food", nameTR: "Comfort Food", nameEN: "Comfort Food", slug: "comfort-food", sortOrder: 8 },
  { id: "cat-makarnalar", nameTR: "Makarnalar", nameEN: "Pasta", slug: "makarnalar", sortOrder: 9 },
  { id: "cat-tatlilar", nameTR: "Tatlılar", nameEN: "Desserts", slug: "tatlilar", sortOrder: 10 },
];

export interface MenuItemData {
  categoryId: string;
  nameTR: string;
  nameEN: string;
  description: string;
  ingredients: string[];
  steps: string[];
  pairings?: string[];
  chefNotes?: string;
  tags: string[];
  heroImage: string;
}

export const fullMenuItems: MenuItemData[] = [
  // KAHVALTI (7)
  {
    categoryId: "cat-kahvalti",
    nameTR: "Smashed Avocado on Sourdough",
    nameEN: "Smashed Avocado on Sourdough",
    description: "Kızarmış ekşi maya ekmeği üzerinde taze ezilmiş avokado, poşe yumurta ve beyaz peynir ile servis edilen modern sporcu kahvaltısı.",
    ingredients: ["Ekşi maya ekmeği", "Taze avokado", "Poşe yumurta", "Beyaz peynir", "Tuz, karabiber", "Limon suyu"],
    steps: ["Ekşi maya ekmeğini kızartın", "Avokadoyu ezin ve limon suyu, tuz ekleyin", "Yumurtayı poşe yapın", "Kızarmış ekmek üzerine avokado, beyaz peynir ve poşe yumurtayı yerleştirin"],
    pairings: ["Taze portakal suyu", "Filtre kahve"],
    chefNotes: "Avokadoyu ezmeyi aşırıya kaçırmayın - kaba doku daha iyi.",
    tags: ["avocado", "healthy", "vegetarian"],
    heroImage: "/images/breakfast/smashed-avocado.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "Southern Thai Roti Set",
    nameEN: "Southern Thai Roti Set",
    description: "Tavada taze kızartılmış Roti ekmeğinin, sahanda yumurta ve batırmalık Massaman köri sosu ile eşleştiği yerel favori.",
    ingredients: ["Roti hamuru", "Sahanda yumurta", "Massaman köri sosu", "Hindistan cevizi sütü", "Fıstık"],
    steps: ["Roti hamurunu tavada kızartın", "Sahanda yumurta pişirin", "Massaman köri sosunu ısıtın", "Roti'yi yumurta ve köri sosu ile servis edin"],
    pairings: ["Thai çayı", "Soğuk süt"],
    chefNotes: "Roti'yi çok ince açın - ince olması lezzeti artırır.",
    tags: ["thai", "local", "roti"],
    heroImage: "/images/breakfast/thai-roti.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "The Brook Big Breakfast",
    nameEN: "The Brook Big Breakfast",
    description: "Yumurta, sosis, bacon, mantar ve fasulye ile hazırlanan doyurucu ve klasik İngiliz kahvaltı tabağı.",
    ingredients: ["Yumurta", "Domuz sosis", "Bacon", "Mantar", "Fırın fasulye", "Kızarmış ekmek", "Domates"],
    steps: ["Sosisleri ve bacon'ı pişirin", "Mantarları soteleyin", "Yumurtaları pişirin", "Fasulyeleri ısıtın", "Tümünü tabağa yerleştirin"],
    pairings: ["İngiliz çayı", "Portakal suyu"],
    chefNotes: "Tüm bileşenleri aynı anda sıcak servis etmek önemli.",
    tags: ["english", "classic", "hearty"],
    heroImage: "/images/breakfast/big-breakfast.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "Tropical Smoothie Bowl",
    nameEN: "Tropical Smoothie Bowl",
    description: "Mango ve muz tabanlı, üzeri taze tropikal meyveler ve granola ile süslenmiş ferahlatıcı vegan kase.",
    ingredients: ["Dondurulmuş mango", "Muz", "Hindistan cevizi sütü", "Granola", "Taze meyveler", "Chia tohumları", "Hindistan cevizi parçaları"],
    steps: ["Mango, muz ve hindistan cevizi sütünü blenderdan geçirin", "Kaseye dökün", "Üzerine granola, taze meyveler ve tohumları yerleştirin"],
    pairings: ["Taze limonata", "Yeşil çay"],
    chefNotes: "Smoothie'yi kalın kıvamda tutun ki üzerine süsler durabilsin.",
    tags: ["smoothie", "vegan", "healthy"],
    heroImage: "/images/breakfast/smoothie-bowl.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "Royal Eggs Benedict",
    nameEN: "Royal Eggs Benedict",
    description: "İngiliz Muffin ekmeği üzerinde poşe yumurta, dana jambon ve ev yapımı hollandez sos ile sunulan kahvaltı klasiği.",
    ingredients: ["İngiliz Muffin", "Poşe yumurta", "Dana jambon", "Hollandez sos", "Tereyağı", "Maydanoz"],
    steps: ["Muffin'i kızartın", "Jambonu kızartın", "Yumurtaları poşe yapın", "Hollandez sosunu hazırlayın", "Tümünü birleştirin"],
    pairings: ["Mimosa", "Cappuccino"],
    chefNotes: "Hollandez sosunun sıcaklığına dikkat edin.",
    tags: ["eggs", "classic", "benedict"],
    heroImage: "/images/breakfast/eggs-benedict.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "American Pancake Stack",
    nameEN: "American Pancake Stack",
    description: "Akçaağaç şurubu, taze meyveler ve pudra şekeri ile servis edilen üç katlı puf Amerikan krep kulesi.",
    ingredients: ["Un", "Yumurta", "Süt", "Kabartma tozu", "Vanilya", "Akçaağaç şurubu", "Taze meyveler", "Pudra şekeri"],
    steps: ["Hamuru hazırlayın", "Pancake'leri pişirin", "Üst üste dizin", "Tereyağı ve şurupla süsleyin"],
    pairings: ["Sıcak çikolata", "Filtre kahve"],
    chefNotes: "Hamuru çok karıştırmayın - hafif pürüzlü olmalı.",
    tags: ["pancake", "american", "sweet"],
    heroImage: "/images/breakfast/pancake-stack.jpg",
  },
  {
    categoryId: "cat-kahvalti",
    nameTR: "Continental Breakfast",
    nameEN: "Continental Breakfast",
    description: "Kruvasan, fırın ürünleri, mevsim meyveleri, yoğurt ve reçel çeşitlerinden oluşan hafif başlangıç tabağı.",
    ingredients: ["Kruvasan", "Fırın ürünleri", "Mevsim meyveleri", "Yoğurt", "Reçel", "Tereyağı", "Bal"],
    steps: ["Kruvasanı ısıtın", "Meyveleri dilimleyin", "Tüm bileşenleri tabağa yerleştirin"],
    pairings: ["Espresso", "Portakal suyu"],
    chefNotes: "Taze fırınlanmış kruvasan bu kahvaltının anahtarı.",
    tags: ["continental", "light", "classic"],
    heroImage: "/images/breakfast/continental.jpg",
  },

  // ÇORBALAR (5)
  {
    categoryId: "cat-corbalar",
    nameTR: "Tom Yum Goong (Creamy)",
    nameEN: "Tom Yum Goong (Creamy)",
    description: "Büyük karidesler ve aromatik otlarla hazırlanan, süt ilavesiyle yumuşatılmış dünyaca ünlü acılı ve ekşili çorba.",
    ingredients: ["Karides", "Limon otu", "Galangal", "Kaffir lime yaprağı", "Acı biber", "Hindistan cevizi sütü", "Mantar", "Balık sosu"],
    steps: ["Suyu kaynatın, aromaları ekleyin", "Karidesleri ekleyin", "Hindistan cevizi sütü ekleyin", "Mantar ve baharatlarla tamamlayın"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Karidesleri fazla pişirmeyin - yumuşak kalmalı.",
    tags: ["thai", "spicy", "soup", "shrimp"],
    heroImage: "/images/soups/tom-yum.jpg",
  },
  {
    categoryId: "cat-corbalar",
    nameTR: "Tom Kha Gai",
    nameEN: "Tom Kha Gai",
    description: "Hindistan cevizi sütü, galangal kökü ve tavuk parçalarıyla yapılan, yumuşak içimli ve aromatik beyaz çorba.",
    ingredients: ["Tavuk göğsü", "Hindistan cevizi sütü", "Galangal", "Limon otu", "Kaffir lime", "Mantar", "Kişniş"],
    steps: ["Hindistan cevizi sütünü kaynatın", "Tavuğu ekleyin", "Aromaları ve mantarı ekleyin", "Misket limonu suyu ile bitirin"],
    pairings: ["Pirinç", "Fried wontons"],
    chefNotes: "Galangal'ı ince dilimleyin - yenilebilir olmalı.",
    tags: ["thai", "coconut", "soup", "chicken"],
    heroImage: "/images/soups/tom-kha.jpg",
  },
  {
    categoryId: "cat-corbalar",
    nameTR: "Khao Tom (Rice Soup)",
    nameEN: "Khao Tom (Rice Soup)",
    description: "Zencefil ve sarımsak aromalı tavuk suyunda pişmiş, yasemin pirinci ve köfte parçaları içeren geleneksel çorba.",
    ingredients: ["Yasemin pirinci", "Tavuk suyu", "Kıyma köftesi", "Zencefil", "Sarımsak", "Yeşil soğan", "Kişniş"],
    steps: ["Tavuk suyunu kaynatın", "Pirinci ekleyin ve pişirin", "Köfteleri ekleyin", "Zencefil ve sarımsakla tatlandırın"],
    pairings: ["Fried garlic", "Soya sosu"],
    chefNotes: "Pilavı aşırı pişirmeyin - yumuşak ama taneli olmalı.",
    tags: ["rice", "soup", "comfort"],
    heroImage: "/images/soups/khao-tom.jpg",
  },
  {
    categoryId: "cat-corbalar",
    nameTR: "Roasted Pumpkin Soup",
    nameEN: "Roasted Pumpkin Soup",
    description: "Fırınlanmış yerel bal kabaklarından yapılan, krema ve kıtır ekmekle servis edilen kadifemsi çorba.",
    ingredients: ["Balkabağı", "Soğan", "Sarımsak", "Sebze suyu", "Krema", "Taze kekik", "Karabiber"],
    steps: ["Balkabağını fırınlayın", "Soğan ve sarımsakla soteleyin", "Blenderdan geçirin", "Krema ile yumuşatın"],
    pairings: ["Kızarmış ekmek", "Beyaz şarap"],
    chefNotes: "Balkabağını karamelize edinceye kadar fırınlayın.",
    tags: ["pumpkin", "creamy", "vegetarian"],
    heroImage: "/images/soups/pumpkin.jpg",
  },
  {
    categoryId: "cat-corbalar",
    nameTR: "Clear Glass Noodle Soup",
    nameEN: "Clear Glass Noodle Soup",
    description: "Berrak tavuk suyu içerisinde şeffaf erişte, sebzeler ve kıyma topları.",
    ingredients: ["Şeffaf erişte", "Tavuk suyu", "Kıyma topları", "Lahana", "Havuç", "Yeşil soğan", "Soya sosu"],
    steps: ["Tavuk suyunu kaynatın", "Erişteyikaynatın", "Sebze ve kıyma toplarını ekleyin", "Soya sosu ile tatlandırın"],
    pairings: ["Kızartılmış sarımsak", "Chili oil"],
    chefNotes: "Erişteyisade ısıtmak yeterli - çok pişmesin.",
    tags: ["noodle", "clear", "light"],
    heroImage: "/images/soups/glass-noodle.jpg",
  },

  // BAŞLANGIÇLAR (5)
  {
    categoryId: "cat-baslangiclar",
    nameTR: "Goong Sarong (Signature)",
    nameEN: "Goong Sarong (Signature)",
    description: "İnce pirinç eriştesine sarılarak altın sarısı kızartılmış, erik soslu çıtır kaplan karidesler (Phuket spesiyali).",
    ingredients: ["Kaplan karidesleri", "Pirinç eriştesi", "Erik sosu", "Kızartma yağı"],
    steps: ["Karidesleri temizleyin", "Pirinç eriştesine sarın", "Derin yağda kızartın", "Erik sosu ile servis edin"],
    pairings: ["Thai sweet chili sauce", "Soğuk bira"],
    chefNotes: "Yağın sıcaklığı çok önemli - 180°C ideal.",
    tags: ["shrimp", "fried", "signature", "phuket"],
    heroImage: "/images/starters/goong-sarong.jpg",
  },
  {
    categoryId: "cat-baslangiclar",
    nameTR: "Salt & Pepper Squid",
    nameEN: "Salt & Pepper Squid",
    description: "Taze karabiber, deniz tuzu ve taze soğanla wok tavada sotelenmiş çıtır kalamar parçaları.",
    ingredients: ["Kalamar", "Deniz tuzu", "Taze karabiber", "Soğan", "Yeşil biber", "Sarımsak"],
    steps: ["Kalamarı halkalar halinde kesin", "Unla karıştırıp kızartın", "Wok'ta baharatlarla soteleyin", "Soğan ve biberle servis edin"],
    pairings: ["Limon dilimleri", "Soğuk içecek"],
    chefNotes: "Kalamarı çok kısa süre pişirin - yoksa sert olur.",
    tags: ["squid", "wok", "crispy"],
    heroImage: "/images/starters/salt-pepper-squid.jpg",
  },
  {
    categoryId: "cat-baslangiclar",
    nameTR: "Satay Mix",
    nameEN: "Satay Mix",
    description: "Zerdeçallı özel marinasyonla ızgara edilmiş tavuk ve domuz şişleri, yanında fıstık sosu ile.",
    ingredients: ["Tavuk", "Domuz", "Zerdeçal", "Limon otu", "Hindistan cevizi sütü", "Fıstık ezmesi", "Soya sosu"],
    steps: ["Etleri marine edin", "Şişlere dizin", "Izgara yapın", "Fıstık sosu ile servis edin"],
    pairings: ["Cucumber relish", "Thai bira"],
    chefNotes: "Marinasyon en az 2 saat olmalı.",
    tags: ["satay", "grilled", "peanut"],
    heroImage: "/images/starters/satay.jpg",
  },
  {
    categoryId: "cat-baslangiclar",
    nameTR: "The Brook's Combo Platter",
    nameEN: "The Brook's Combo Platter",
    description: "Tavuk kanat, soğan halkası, sigara böreği ve kalamar tavadan oluşan zengin atıştırma tabağı.",
    ingredients: ["Tavuk kanat", "Soğan", "Yufka", "Kalamar", "Kızartma malzemesi"],
    steps: ["Her bileşeni ayrı hazırlayın", "Kızartın", "Tabağa yerleştirin", "Çeşitli soslarla servis edin"],
    pairings: ["Ranch sos", "BBQ sos", "Sweet chili"],
    chefNotes: "Tüm bileşenleri aynı anda sıcak servis edin.",
    tags: ["combo", "fried", "sharing"],
    heroImage: "/images/starters/combo-platter.jpg",
  },
  {
    categoryId: "cat-baslangiclar",
    nameTR: "Loaded Nachos",
    nameEN: "Loaded Nachos",
    description: "Baharatlı kıyma, erimiş peynir, salsa ve jalapeno ile fırınlanmış mısır cipsi şöleni.",
    ingredients: ["Tortilla cipsi", "Kıyma", "Cheddar peyniri", "Salsa", "Jalapeno", "Ekşi krema"],
    steps: ["Kıymayı baharatla pişirin", "Cipsleri tabağa yerleştirin", "Kıyma ve peynir ekleyin", "Fırınlayın ve soslarla servis edin"],
    pairings: ["Guacamole", "Margarita"],
    chefNotes: "Peynir tamamen eriyene kadar fırınlayın.",
    tags: ["nachos", "cheese", "tex-mex"],
    heroImage: "/images/starters/nachos.jpg",
  },

  // SALATALAR (4)
  {
    categoryId: "cat-salatalar",
    nameTR: "Spicy Seafood Salad (Yam Talay)",
    nameEN: "Spicy Seafood Salad (Yam Talay)",
    description: "Karides, kalamar ve midyenin kereviz sapı, soğan ve acı-ekşi sosla harmanlandığı sıcak salata.",
    ingredients: ["Karides", "Kalamar", "Midye", "Kereviz sapı", "Soğan", "Misket limonu", "Acı biber", "Kişniş"],
    steps: ["Deniz ürünlerini haşlayın", "Sebzeleri doğrayın", "Acı-ekşi sos hazırlayın", "Tümünü karıştırıp servis edin"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Deniz ürünlerini fazla pişirmeyin.",
    tags: ["seafood", "spicy", "thai"],
    heroImage: "/images/salads/yam-talay.jpg",
  },
  {
    categoryId: "cat-salatalar",
    nameTR: "Som Tum Thai",
    nameEN: "Som Tum Thai",
    description: "Yeşil papaya rendesi, domates ve fıstığın havan'da dövülerek hazırlandığı meşhur Tayland salatası.",
    ingredients: ["Yeşil papaya", "Cherry domates", "Fıstık", "Uzun fasulye", "Sarımsak", "Acı biber", "Palm şekeri", "Balık sosu"],
    steps: ["Papayayıjüliyen doğrayın", "Havanda sarımsak ve biber dövün", "Domates ve fasulye ekleyin", "Papaya ve fıstık ekleyip karıştırın"],
    pairings: ["Sticky rice", "Grilled chicken"],
    chefNotes: "Havanda dövmek geleneksel metot - daha lezzetli.",
    tags: ["papaya", "thai", "spicy"],
    heroImage: "/images/salads/som-tum.jpg",
  },
  {
    categoryId: "cat-salatalar",
    nameTR: "Thai Salmon Salad",
    nameEN: "Thai Salmon Salad",
    description: "Sashimi kalitesinde çiğ somon küplerinin misket limonu, sarımsak ve nane sosuyla marine edildiği tabak.",
    ingredients: ["Taze somon", "Misket limonu", "Nane", "Kişniş", "Sarımsak", "Acı biber", "Balık sosu"],
    steps: ["Somonu küp küp doğrayın", "Sos hazırlayın", "Somonu sosla marine edin", "Taze otlarla süsleyin"],
    pairings: ["White wine", "Wasabi"],
    chefNotes: "Somon sashimi grade olmalı - çok taze.",
    tags: ["salmon", "raw", "thai"],
    heroImage: "/images/salads/salmon-salad.jpg",
  },
  {
    categoryId: "cat-salatalar",
    nameTR: "Classic Caesar Salad",
    nameEN: "Classic Caesar Salad",
    description: "Romaine marulu, ızgara tavuk, parmesan, bacon ve krutonların orijinal ançuezli sosla buluşması.",
    ingredients: ["Romaine marul", "Izgara tavuk", "Parmesan", "Bacon", "Kruton", "Ançuez", "Yumurta sarısı", "Zeytinyağı"],
    steps: ["Caesar sos hazırlayın", "Tavuğu ızgara yapın", "Marulu yıkayın", "Tüm malzemeleri karıştırın"],
    pairings: ["Beyaz şarap", "Limonata"],
    chefNotes: "Sosu tam öncesinde hazırlayın - taze olmalı.",
    tags: ["caesar", "chicken", "classic"],
    heroImage: "/images/salads/caesar.jpg",
  },

  // PHUKET İMZA YEMEKLERİ (9)
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Crispy Pork Red Curry",
    nameEN: "Pad Prik Gaeng Moo Krob",
    description: "Wok tavada kırmızı köri macunu ve taze fasulye ile sotelenmiş çıtır domuz göbeği.",
    ingredients: ["Domuz göbeği", "Kırmızı köri macunu", "Taze fasulye", "Kaffir lime", "Thai fesleğeni", "Palm şekeri"],
    steps: ["Domuz göbeğini kızartın", "Köri macununu soteleyin", "Fasulyeleri ekleyin", "Çıtır domuzu ekleyin ve karıştırın"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Domuz çok çıtır olmalı - derisini iyi kurulayın.",
    tags: ["pork", "curry", "crispy", "signature"],
    heroImage: "/images/phuket/crispy-pork-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Gaeng Poo (Crab Curry)",
    nameEN: "Gaeng Poo (Crab Curry)",
    description: "Taze yengeç eti ve betel yapraklarıyla hazırlanan, yanında pirinç eriştesiyle sunulan Chalong spesiyali sarı köri.",
    ingredients: ["Yengeç", "Sarı köri macunu", "Betel yaprakları", "Hindistan cevizi sütü", "Pirinç eriştesi", "Yumurta"],
    steps: ["Yengeç etini çıkarın", "Köri sosunu hazırlayın", "Yengeç ve betel ekleyin", "Pirinç eriştesiyle servis edin"],
    pairings: ["Taze sebzeler", "Thai whiskey"],
    chefNotes: "Yengeç çok taze olmalı - aynı gün.",
    tags: ["crab", "curry", "chalong", "signature"],
    heroImage: "/images/phuket/crab-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Mee Hokkien",
    nameEN: "Mee Hokkien",
    description: "Sarı yumurtalı kalın eriştenin deniz ürünleri ve yumurta ile wok tavada sulu kıvamda sotelendiği yerel lezzet.",
    ingredients: ["Hokkien eriştesi", "Karides", "Kalamar", "Yumurta", "Lahana", "Soya sosu", "Istiridye sosu"],
    steps: ["Erişteyihaşlayın", "Deniz ürünlerini soteleyin", "Erişteve sosları ekleyin", "Yumurta ekleyip karıştırın"],
    pairings: ["Pickled chili", "Thai bira"],
    chefNotes: "Wok çok sıcak olmalı - yüksek ateş önemli.",
    tags: ["noodles", "seafood", "wok"],
    heroImage: "/images/phuket/mee-hokkien.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Massaman Curry Chicken",
    nameEN: "Massaman Curry Chicken",
    description: "Patates, soğan ve fıstık ile pişmiş yumuşak tavuk butları.",
    ingredients: ["Tavuk butu", "Massaman köri macunu", "Patates", "Soğan", "Fıstık", "Hindistan cevizi sütü", "Tamarind"],
    steps: ["Tavuğu marine edin", "Köri sosunu hazırlayın", "Patates ve soğan ekleyin", "Düşük ateşte pişirin"],
    pairings: ["Roti", "Thai bira"],
    chefNotes: "Uzun süre pişirin - tavuk çok yumuşak olmalı.",
    tags: ["chicken", "massaman", "curry"],
    heroImage: "/images/phuket/massaman-chicken.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Duck Red Curry",
    nameEN: "Duck Red Curry",
    description: "Fırınlanmış ördek göğsü, ananas ve üzüm tanelerinin kırmızı köri sosundaki egzotik uyumu.",
    ingredients: ["Ördek göğsü", "Kırmızı köri macunu", "Ananas", "Üzüm", "Hindistan cevizi sütü", "Thai fesleğeni"],
    steps: ["Ördeği fırınlayın", "Köri sosunu hazırlayın", "Ananas ve üzüm ekleyin", "Ördek dilimlerini ekleyin"],
    pairings: ["Yasemin pilavı", "Red wine"],
    chefNotes: "Ördek orta pişmiş olmalı - pembe kalabilir.",
    tags: ["duck", "curry", "pineapple"],
    heroImage: "/images/phuket/duck-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Gaeng Phed Nua (Beef Red Curry)",
    nameEN: "Gaeng Phed Nua",
    description: "Tender slices of beef simmered in red curry with bamboo shoots, Thai eggplant, and sweet basil.",
    ingredients: ["Sığır eti", "Kırmızı köri macunu", "Bambu filizi", "Thai patlıcanı", "Thai fesleğeni", "Kırmızı biber", "Balık sosu"],
    steps: ["Eti dilimleyin", "Köri macununu soteleyin", "Bambu ve patlıcanı ekleyin", "Eti ekleyip pişirin"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Bambu filizi çok önemli - otantik tat için şart.",
    tags: ["beef", "curry", "bamboo"],
    heroImage: "/images/phuket/beef-red-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Gaeng Kua Sapparot Goong",
    nameEN: "Pineapple Prawn Curry",
    description: "Phuket style red curry with prawns and fresh pineapple.",
    ingredients: ["Karides", "Kırmızı köri macunu", "Taze ananas", "Hindistan cevizi sütü", "Thai fesleğeni", "Kaffir lime"],
    steps: ["Karidesleri temizleyin", "Köri sosunu hazırlayın", "Ananası ekleyin", "Karidesleri son anda ekleyin"],
    pairings: ["Yasemin pilavı", "White wine"],
    chefNotes: "Ananas asidi deniz ürünü kokusunu nötrler.",
    tags: ["prawn", "curry", "pineapple", "signature"],
    heroImage: "/images/phuket/pineapple-prawn-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Gaeng Phed Talay",
    nameEN: "Seafood Red Curry",
    description: "Mixed seafood in rich red curry sauce with kaffir lime leaves and basil.",
    ingredients: ["Karışık deniz ürünleri", "Kırmızı köri macunu", "Kaffir lime yaprağı", "Thai fesleğeni", "Uzun fasulye", "Hindistan cevizi sütü"],
    steps: ["Köri sosunu hazırlayın", "Deniz ürünlerini ekleyin", "Kaffir lime ve fesleğen ekleyin", "Kısa süre pişirin"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Deniz ürünlerini fazla pişirmeyin - sert olur.",
    tags: ["seafood", "curry", "mixed"],
    heroImage: "/images/phuket/seafood-red-curry.jpg",
  },
  {
    categoryId: "cat-phuket-imza",
    nameTR: "Pad Kra Pao Wagyu",
    nameEN: "Pad Kra Pao Wagyu",
    description: "Wagyu etinin taze fesleğen ve acı biberle wok tavada sotelenip, üzerine sahanda yumurta konulduğu premium sokak lezzeti.",
    ingredients: ["Wagyu dana", "Thai fesleğeni", "Acı biber", "Sarımsak", "Soya sosu", "Istiridye sosu", "Sahanda yumurta"],
    steps: ["Wok'u çok ısıtın", "Sarımsak ve biberi soteleyin", "Wagyu'yu ekleyin", "Fesleğen ekleyin", "Sahanda yumurta ile servis edin"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Wok çok sıcak olmalı - hızlı pişirme önemli.",
    tags: ["wagyu", "basil", "premium", "signature"],
    heroImage: "/images/phuket/pad-krapao-wagyu.jpg",
  },

  // DENİZ ÜRÜNLERİ (3)
  {
    categoryId: "cat-deniz-urunleri",
    nameTR: "Fried Sea Bass (Tod Nam Pla)",
    nameEN: "Fried Sea Bass (Tod Nam Pla)",
    description: "Kelebek şeklinde açılıp kızartılmış bütün levreğin, karamelize balık sosu ve mango salatasıyla sunumu.",
    ingredients: ["Levrek", "Balık sosu", "Palm şekeri", "Mango", "Soğan", "Kişniş", "Acı biber"],
    steps: ["Levreği kelebek açın", "Derin yağda kızartın", "Balık sosunu karamelize edin", "Mango salatası hazırlayın", "Servis edin"],
    pairings: ["Yasemin pilavı", "Thai bira"],
    chefNotes: "Yağ çok sıcak olmalı - çıtır kabuk için.",
    tags: ["seabass", "fried", "mango"],
    heroImage: "/images/seafood/fried-seabass.jpg",
  },
  {
    categoryId: "cat-deniz-urunleri",
    nameTR: "Steamed Sea Bass (Lime Sauce)",
    nameEN: "Steamed Sea Bass (Lime Sauce)",
    description: "Buharda pişmiş bütün levreğin, sarımsak, acı biber ve misket limonu suyu sosuyla sıcak servis edildiği sağlıklı seçenek.",
    ingredients: ["Levrek", "Sarımsak", "Acı biber", "Misket limonu", "Soya sosu", "Zencefil", "Kişniş"],
    steps: ["Levreği temizleyin", "Buharda pişirin", "Sıcak sos hazırlayın", "Sosu balığın üzerine dökün"],
    pairings: ["Yasemin pilavı", "Beyaz şarap"],
    chefNotes: "Buhar çok sıcak olmalı - hızlı pişirme.",
    tags: ["seabass", "steamed", "healthy"],
    heroImage: "/images/seafood/steamed-seabass.jpg",
  },
  {
    categoryId: "cat-deniz-urunleri",
    nameTR: "Grilled Tiger Prawns",
    nameEN: "Grilled Tiger Prawns",
    description: "Sarımsaklı tereyağı veya Thermidor sos seçeneğiyle sunulan, ızgara dev kaplan karidesleri.",
    ingredients: ["Kaplan karidesleri", "Sarımsak", "Tereyağı", "Maydanoz", "Limon", "Thermidor sos (opsiyonel)"],
    steps: ["Karidesleri temizleyin", "Marine edin", "Izgara yapın", "Sarımsaklı tereyağı ile servis edin"],
    pairings: ["Beyaz şarap", "Limon dilimleri"],
    chefNotes: "Karidesleri fazla pişirmeyin - yumuşak kalmalı.",
    tags: ["prawns", "grilled", "garlic"],
    heroImage: "/images/seafood/grilled-prawns.jpg",
  },

  // BATI ANA YEMEKLERİ (6)
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Australian Ribeye Steak",
    nameEN: "Australian Ribeye Steak",
    description: "Mevsim sebzeleri ve patates kızartması eşliğinde sunulan, ızgara edilmiş 250 gramlık Avustralya antrikot.",
    ingredients: ["Ribeye steak (250g)", "Mevsim sebzeleri", "Patates", "Tereyağı", "Tuz", "Karabiber"],
    steps: ["Eti oda sıcaklığına getirin", "Izgara yapın", "Dinlendirin", "Sebze ve patatesle servis edin"],
    pairings: ["Red wine", "Pepper sauce"],
    chefNotes: "Et dinlendirilmeli - suyunu korumalı.",
    tags: ["beef", "steak", "grilled"],
    heroImage: "/images/western/ribeye.jpg",
  },
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Surf & Turf",
    nameEN: "Surf & Turf",
    description: "Izgara antrikot ve dev kaplan karideslerin aynı tabakta buluştuğu zengin ana yemek.",
    ingredients: ["Antrikot", "Kaplan karidesleri", "Sarımsaklı tereyağı", "Sebzeler", "Patates"],
    steps: ["Antrikotu ızgara yapın", "Karidesleri ızgara yapın", "Sarımsaklı tereyağı ile servis edin"],
    pairings: ["Red wine", "Beyaz şarap"],
    chefNotes: "Her iki proteini de aynı anda hazırlayın.",
    tags: ["steak", "prawns", "premium"],
    heroImage: "/images/western/surf-turf.jpg",
  },
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Grilled Pork Chop",
    nameEN: "Grilled Pork Chop",
    description: "Kemikli domuz pirzola, elma püresi veya mantar sos ve patates püresi ile.",
    ingredients: ["Domuz pirzola", "Elma", "Mantar", "Patates", "Krema", "Taze kekik"],
    steps: ["Pirzolayı marine edin", "Izgara yapın", "Elma püresi veya mantar sos hazırlayın", "Patates püresi ile servis edin"],
    pairings: ["Apple cider", "White wine"],
    chefNotes: "Pirzola orta pişmiş olmalı - yumuşak.",
    tags: ["pork", "grilled", "apple"],
    heroImage: "/images/western/pork-chop.jpg",
  },
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Chicken Cordon Bleu",
    nameEN: "Chicken Cordon Bleu",
    description: "Jambon ve peynir dolgulu, panelenerek kızartılmış tavuk göğsü, yanında patates püresi ile.",
    ingredients: ["Tavuk göğsü", "Jambon", "Swiss peyniri", "Galeta unu", "Yumurta", "Un"],
    steps: ["Tavuğu açıp inceletin", "Jambon ve peynir yerleştirin", "Rulo yapın", "Panele edip kızartın"],
    pairings: ["Beyaz şarap", "Dijon sos"],
    chefNotes: "Tavuk tamamen pişmiş olmalı.",
    tags: ["chicken", "fried", "cheese"],
    heroImage: "/images/western/cordon-bleu.jpg",
  },
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Grilled Salmon Fillet",
    nameEN: "Grilled Salmon Fillet",
    description: "Limonlu tereyağı sosu, kuşkonmaz ve trüflü patates püresi eşliğinde ızgara somon fileto.",
    ingredients: ["Somon fileto", "Limon", "Tereyağı", "Kuşkonmaz", "Patates", "Trüf yağı"],
    steps: ["Somonu ızgara yapın", "Limonlu tereyağı sos hazırlayın", "Kuşkonmaz soteleyin", "Trüflü püre ile servis edin"],
    pairings: ["White wine", "Champagne"],
    chefNotes: "Somon orta pişmiş olmalı - içi pembe.",
    tags: ["salmon", "grilled", "truffle"],
    heroImage: "/images/western/grilled-salmon.jpg",
  },
  {
    categoryId: "cat-bati-anayemekleri",
    nameTR: "Fish & Chips",
    nameEN: "Fish & Chips",
    description: "Tempura hamuruyla kaplanıp kızartılmış yerel balık fileto, patates kızartması ve tartar sos.",
    ingredients: ["Balık fileto", "Tempura hamuru", "Patates", "Tartar sos", "Limon"],
    steps: ["Balığı tempura hamuruyla kaplayın", "Kızartın", "Patates kızartması hazırlayın", "Tartar sos ile servis edin"],
    pairings: ["Beer", "Limonata"],
    chefNotes: "Hamur çok çıtır olmalı - soğuk hamur kullanın.",
    tags: ["fish", "fried", "classic"],
    heroImage: "/images/western/fish-chips.jpg",
  },

  // COMFORT FOOD (2)
  {
    categoryId: "cat-comfort-food",
    nameTR: "Aussie Beef Burger",
    nameEN: "Aussie Beef Burger",
    description: "Pancar turşusu, ızgara ananas, yumurta ve bacon ile hazırlanan Chalong favorisi ev yapımı burger.",
    ingredients: ["Dana kıyma", "Burger ekmeği", "Pancar turşusu", "Ananas", "Yumurta", "Bacon", "Cheddar", "Marul"],
    steps: ["Köfteyi şekillendirin", "Izgara yapın", "Ekmeği kızartın", "Tüm malzemeleri birleştirin"],
    pairings: ["Beer", "Milkshake"],
    chefNotes: "Köfte %80/20 yağ oranında olmalı.",
    tags: ["burger", "beef", "aussie"],
    heroImage: "/images/comfort/burger.jpg",
  },
  {
    categoryId: "cat-comfort-food",
    nameTR: "Brook Club Sandwich",
    nameEN: "Brook Club Sandwich",
    description: "Izgara tavuk, bacon, yumurta ve peynirle hazırlanan üç katlı klasik tost sandviç.",
    ingredients: ["Tost ekmeği", "Izgara tavuk", "Bacon", "Yumurta", "Marul", "Domates", "Mayonez"],
    steps: ["Ekmeği kızartın", "Tavuk ve bacon'ı hazırlayın", "Katmanları oluşturun", "Üçgen kesin"],
    pairings: ["Patates cipsi", "Lemonade"],
    chefNotes: "Ekmeği hafifçe kızartın - çok sert olmasın.",
    tags: ["sandwich", "chicken", "club"],
    heroImage: "/images/comfort/club-sandwich.jpg",
  },

  // MAKARNALAR (4)
  {
    categoryId: "cat-makarnalar",
    nameTR: "Pineapple Fried Rice",
    nameEN: "Pineapple Fried Rice",
    description: "Yarım ananas içerisinde sunulan karidesli, körili, fıstıklı ve kuru üzümlü görsel şölen.",
    ingredients: ["Pilav", "Karides", "Ananas", "Köri tozu", "Fıstık", "Kuru üzüm", "Yeşil soğan"],
    steps: ["Pilavı pişirin", "Karidesleri soteleyin", "Köri ve malzemeleri ekleyin", "Ananas içinde servis edin"],
    pairings: ["Thai bira", "White wine"],
    chefNotes: "Ananası boşaltırken dikkatli olun.",
    tags: ["rice", "pineapple", "curry", "shrimp"],
    heroImage: "/images/pasta/pineapple-rice.jpg",
  },
  {
    categoryId: "cat-makarnalar",
    nameTR: "Creamy Truffle Mushroom Pasta",
    nameEN: "Creamy Truffle Mushroom Pasta",
    description: "Trüf yağı, porçini mantarı ve krema soslu Fettuccine veya Penne.",
    ingredients: ["Fettuccine", "Porçini mantarı", "Krema", "Trüf yağı", "Parmesan", "Sarımsak"],
    steps: ["Makarnayı haşlayın", "Mantarları soteleyin", "Krema ekleyin", "Trüf yağı ile bitirin"],
    pairings: ["White wine", "Parmesan"],
    chefNotes: "Trüf yağını son anda ekleyin - aromasını korur.",
    tags: ["pasta", "truffle", "mushroom"],
    heroImage: "/images/pasta/truffle-pasta.jpg",
  },
  {
    categoryId: "cat-makarnalar",
    nameTR: "Spaghetti Carbonara",
    nameEN: "Spaghetti Carbonara",
    description: "Bacon, yumurta sarısı, karabiber ve parmesan peyniriyle hazırlanan orijinal Roma usulü makarna.",
    ingredients: ["Spaghetti", "Guanciale/Bacon", "Yumurta sarısı", "Parmesan", "Karabiber"],
    steps: ["Makarnayı haşlayın", "Bacon'ı kızartın", "Yumurta ve peynir karışımı hazırlayın", "Tümünü birleştirin"],
    pairings: ["White wine", "Garlic bread"],
    chefNotes: "Yumurta pişmemeli - kremamsı olmalı.",
    tags: ["pasta", "carbonara", "classic"],
    heroImage: "/images/pasta/carbonara.jpg",
  },
  {
    categoryId: "cat-makarnalar",
    nameTR: "Spicy Seafood Spaghetti",
    nameEN: "Spicy Seafood Spaghetti",
    description: "Zeytinyağı, sarımsak, acı biber ve taze deniz ürünleriyle sotelenmiş spagetti.",
    ingredients: ["Spaghetti", "Karides", "Kalamar", "Midye", "Sarımsak", "Acı biber", "Beyaz şarap"],
    steps: ["Makarnayı haşlayın", "Deniz ürünlerini soteleyin", "Makarnayı ekleyin", "Beyaz şarap ile deglaze edin"],
    pairings: ["White wine", "Garlic bread"],
    chefNotes: "Deniz ürünlerini fazla pişirmeyin.",
    tags: ["pasta", "seafood", "spicy"],
    heroImage: "/images/pasta/seafood-spaghetti.jpg",
  },

  // TATLILAR (5)
  {
    categoryId: "cat-tatlilar",
    nameTR: "Oh Aew (Phuket Shaved Ice)",
    nameEN: "Oh Aew (Phuket Shaved Ice)",
    description: "Muz jölesi, kırmızı fasulye ve şuruplu buz rendesinden oluşan sadece Phuket'e özgü serinletici tatlı.",
    ingredients: ["Buz rendesi", "Muz jölesi", "Kırmızı fasulye", "Palm şekeri şurubu", "Hindistan cevizi sütü"],
    steps: ["Buzu rendeleyin", "Malzemeleri yerleştirin", "Şurup ve hindistan cevizi sütü dökün"],
    pairings: ["Thai çayı"],
    chefNotes: "Çok soğuk servis edin.",
    tags: ["ice", "phuket", "local", "dessert"],
    heroImage: "/images/desserts/oh-aew.jpg",
  },
  {
    categoryId: "cat-tatlilar",
    nameTR: "Mango Sticky Rice",
    nameEN: "Mango Sticky Rice",
    description: "Taze sarı mango dilimleri ve tatlı hindistan cevizi sütüyle pişmiş yapışkan pirinç.",
    ingredients: ["Sticky rice", "Taze mango", "Hindistan cevizi sütü", "Şeker", "Tuz"],
    steps: ["Pirinçleri ıslatın", "Pişirin", "Hindistan cevizi sütü ile karıştırın", "Mango ile servis edin"],
    pairings: ["Thai çayı"],
    chefNotes: "Mango çok olgun ve tatlı olmalı.",
    tags: ["mango", "thai", "dessert"],
    heroImage: "/images/desserts/mango-sticky-rice.jpg",
  },
  {
    categoryId: "cat-tatlilar",
    nameTR: "Coconut Ice Cream",
    nameEN: "Coconut Ice Cream",
    description: "Hindistan cevizi kabuğu içinde, fıstık ve jöle parçalarıyla sunulan ev yapımı dondurma.",
    ingredients: ["Hindistan cevizi sütü", "Şeker", "Fıstık", "Jöle", "Mısır taneleri"],
    steps: ["Dondurma karışımı hazırlayın", "Dondurucuda bekletin", "Hindistan cevizi kabuğunda servis edin"],
    pairings: ["Wafer"],
    chefNotes: "Taze hindistan cevizi kullanın.",
    tags: ["coconut", "ice-cream", "dessert"],
    heroImage: "/images/desserts/coconut-icecream.jpg",
  },
  {
    categoryId: "cat-tatlilar",
    nameTR: "Warm Brownie",
    nameEN: "Warm Brownie",
    description: "Sıcak servis edilen çikolatalı brownie ve yanında bir top vanilyalı dondurma.",
    ingredients: ["Çikolata", "Tereyağı", "Şeker", "Yumurta", "Un", "Vanilya dondurması"],
    steps: ["Brownie hamuru hazırlayın", "Fırınlayın", "Sıcak servis edin", "Dondurma ile birleştirin"],
    pairings: ["Espresso", "Süt"],
    chefNotes: "Brownie içi ıslak kalmalı.",
    tags: ["chocolate", "brownie", "dessert"],
    heroImage: "/images/desserts/brownie.jpg",
  },
  {
    categoryId: "cat-tatlilar",
    nameTR: "Grilled Banana Boat",
    nameEN: "Grilled Banana Boat",
    description: "Kabuğuyla ızgara edilmiş muz, ortası yarılıp içine eritilmiş çikolata ve fıstık parçaları, yanında dondurma ile.",
    ingredients: ["Muz", "Çikolata parçaları", "Fıstık", "Vanilya dondurması", "Bal"],
    steps: ["Muzun ortasını kesin", "Çikolata ve fıstık yerleştirin", "Izgara yapın", "Dondurma ile servis edin"],
    pairings: ["Vanilla ice cream"],
    chefNotes: "Muz yumuşak ama formunu korumalı.",
    tags: ["banana", "grilled", "dessert"],
    heroImage: "/images/desserts/banana-boat.jpg",
  },
];
